<?php
#
# DO NOT EDIT THIS FILE
# ---------------------
# The Semiologic theme features a custom.php feature. This allows to hook into
# the template without editing its php files. That way, you won't need to worry
# about losing your changes when you upgrade your site.
#
# You'll find detailed sample files in the custom-samples folder
#

/*
Template Name: Archives
*/

if ( isset($_GET['mon']) )
{
	$mon = explode('-', $_GET['mon']);

	if ( count($mon) == 2 )
	{
		wp_redirect(get_month_link($mon[0], $mon[1]), 301);
	}
	else
	{
		global $wp_the_query;
		wp_redirect(get_permalink($wp_the_query->get_queried_object_id()), 301);
	}
	die;
}

include sem_path . '/index.php';
?>