<?php
#
# DO NOT EDIT THIS FILE
# ---------------------
# You would lose your changes when you upgrade your site. Use php widgets instead.
#

#
# initialize
#

include dirname(__FILE__) . '/inc/init.php';

# set content width
switch ( $sem_options['active_layout'] ) {
case 'm':
	$content_width = 560;
	break;
case 'mm':
case 'mms':
case 'smm':
	$content_width = 690;
	break;
case 'mmm':
	$content_width = 890;
	break;
default:
	$content_width = 490;
	break;
}

# kill page comments
if ( !is_admin() )
	add_filter('option_page_comments', 'false');

# kill resource hungry queries
remove_action('wp_head', 'index_rel_link');
remove_action('wp_head', 'parent_post_rel_link');
remove_action('wp_head', 'start_post_rel_link');
remove_action('wp_head', 'adjacent_posts_rel_link');


include sem_path . '/inc/panels.php';
include sem_path . '/inc/widgets.php';
include sem_path . '/inc/template.php';

if ( file_exists(sem_path . '/custom.php') )
	include sem_path . '/custom.php';

if ( is_admin() ) {
	if ( !function_exists('load_multipart_entry') ) :
	function load_multipart_entry() {
		include dirname(__FILE__) . '/inc/multipart-entry/multipart-entry.php';
	} # load_multipart_entry()
	endif;

	function sem_header_admin() {
		include_once sem_path . '/inc/header.php';
	}
	
	add_action('load-appearance_page_header', 'sem_header_admin');
	foreach ( array('post.php', 'post-new.php', 'page.php', 'page-new.php') as $hook) {
		add_action("load-$hook", 'sem_header_admin');
		add_action("load-$hook", 'load_multipart_entry');
	}
	
	function sem_layout_admin() {
		include_once sem_path . '/inc/layout.php';
	}
	
	add_action('load-appearance_page_layout', 'sem_layout_admin');
	
	function sem_skin_admin() {
		include_once sem_path . '/inc/skin.php';
	}
	
	add_action('load-appearance_page_skin', 'sem_skin_admin');
}
?>