<?php
#
# DO NOT EDIT THIS FILE
# ---------------------
# The Semiologic theme features a custom.php feature. This allows to hook into
# the template without editing its php files. That way, you won't need to worry
# about losing your changes when you upgrade your site.
#
# You'll find detailed sample files in the custom-samples folder
#

?><!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml"><head><title><?php
if ( $title = wp_title('&raquo;', false) )
{
	echo $title;
}
else
{
	bloginfo('description');
}
?></title>
<meta http-equiv="Content-Type" content="text/html; charset=<?php bloginfo('charset'); ?>" />
<link rel="alternate" type="application/rss+xml" title="<?php _e('RSS feed'); ?>" href="<?php bloginfo('rss2_url'); ?>" />
<link rel="pingback" href="<?php bloginfo('pingback_url'); ?>" />
<?php do_action('wp_head'); ?>
</head>
<body class="<?php do_action('display_page_class'); ?>">
<?php
do_action('before_the_wrapper');
?>
<div id="ext_wrapper">
<div id="shadow_top"><div class="hidden"></div></div>
<div id="shadow">
<div id="wrapper">

<?php
do_action('the_header');
do_action('the_header_boxes');
?>

<div id="body" class="body">
<div id="ext_main">
<div id="main" class="main">
<div class="pad">