<?php
#
# DO NOT EDIT THIS FILE
# ---------------------
# The Semiologic theme features a custom.php feature. This allows to hook into
# the template without editing its php files. That way, you won't need to worry
# about losing your changes when you upgrade your site.
#
# You'll find detailed sample files in the custom-samples folder
#


/*
Template Name: Sales Letter
*/

add_filter('active_layout', 'force_m');
add_filter('active_width', 'force_letter');

# show header
?><!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml"><head><title><?php
if ( $title = wp_title('&raquo;', false) )
{
	echo $title;
}
else
{
	bloginfo('description');
}
?></title>
<meta http-equiv="Content-Type" content="text/html; charset=<?php bloginfo('charset'); ?>" />
<link rel="alternate" type="application/rss+xml" title="<?php _e('RSS feed'); ?>" href="<?php bloginfo('rss2_url'); ?>" />
<link rel="pingback" href="<?php bloginfo('pingback_url'); ?>" />
<?php do_action('wp_head'); ?>
</head>
<body class="<?php do_action('display_page_class'); ?>">
<div id="ext_wrapper">
<div id="shadow_top"><div class="hidden"></div></div>
<div id="shadow">
<div id="wrapper">
<div id="body" class="body">
<div id="ext_main">
<div id="main" class="main">
<div class="pad">
<?php

# show page
the_post();
?>
<div class="entry" id="entry-<?php the_ID(); ?>">
<?php
		do_action('the_entry');
?>
</div>
<?php

# show footer
?></div>
</div><!-- #main -->
</div><!-- #ext_main -->
</div><!-- #body -->
</div><!-- #wrapper -->
</div><!-- #shadow -->
<div id="shadow_bottom"><div class="hidden"></div></div>
</div><!-- #ext_wrapper -->
<?php
do_action('display_canvas_spacer');
do_action('wp_footer');
?>
</body>
</html>