<?php
#
# DO NOT EDIT THIS FILE
# ---------------------
# The Semiologic theme features a custom.php feature. This allows to hook into
# the template without editing its php files. That way, you won't need to worry
# about losing your changes when you upgrade your site.
#
# You'll find detailed sample files in the custom-samples folder
#


/*
Template Name: Sales Letter
*/

add_filter('active_layout', array('sem_template', 'strip_sidebars'));
add_filter('active_width', array('sem_template', 'force_letter'));

# show header
?><!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml"><head><title><?php
if ( $title = trim(wp_title('&#8211;', false)) ) {
	if ( strpos($title, '&#8211;') === 0 )
		$title = trim(substr($title, strlen('&#8211;')));
	echo $title;
} else {
	bloginfo('description');
}
?></title>
<meta http-equiv="Content-Type" content="text/html; charset=<?php bloginfo('charset'); ?>" />
<link rel="alternate" type="application/rss+xml" title="<?php _e('RSS feed'); ?>" href="<?php bloginfo('rss2_url'); ?>" />
<link rel="pingback" href="<?php bloginfo('pingback_url'); ?>" />
<?php do_action('wp_head'); ?>
</head>
<body class="<?php echo implode(' ', get_body_class(array('skin', 'custom'))); ?>"><div id="ext_wrapper">
<div id="wrapper">
<div id="body" class="body">
<div id="ext_main">
<div id="main" class="main">
<div class="pad">
<?php

# show page
the_post();
?>
<div class="entry" id="entry-<?php the_ID(); ?>">
<?php
		do_action('the_entry');
?>
</div>
<?php

# show footer
?></div>
</div><!-- #main -->
</div><!-- #ext_main -->
</div><!-- #body -->
</div><!-- #wrapper -->
</div><!-- #ext_wrapper -->
<?php
do_action('display_canvas_spacer');
do_action('wp_footer');
?>
</body>
</html>